name: docs

on: [push]

env:
  nim-version: stable
  nim-src: src/trayx
  deploy-dir: .gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: ${{ env.nim-version }}
      - run: nimble build
      - run: nim doc --index:on --project --out:${{ env.deploy-dir }} ${{ env.nim-src }}
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}