name: Test

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        nim-version:
          - stable
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: '${{ matrix.nim-version }}'
      - name: Running test
        run: nimble test -Y
